sudo: required

services:
  - docker

before_install:
  - docker build -t quay.io/jaeddy/dockstore-tool-helloworld .
  - pip2.7 install --user setuptools==28.8.0

install:
  - pip2.7 install --user cwl-runner cwltool==1.0.20161114152756 schema-salad==1.18.20161005190847 avro==1.8.1

script:
  - cwltool --non-strict Dockstore.cwl test.json
